apiVersion: batch/v1
kind: Job
metadata:
  name: jsbmiwebapp-job
spec:
  template:
    spec:
      containers:
      - name: jsbmiwebapp-job
        image: yash5090/jsbmiwebapp:latest
        ports:
        - containerPort: 5000
      restartPolicy: OnFailure
