apiVersion: apps/v1
kind: Deployment
metadata:
  name: jsbmiwebapp-deployment
spec:
  replicas: 6 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: jsbmiwebapp
  template:
    metadata:
      labels:
        app: jsbmiwebapp
    spec:
      containers:
        - name: jsbmiwebapp
          image: yash5090/jsbmiwebapp:latest # Replace with the actual image tag
          ports:
            - containerPort: 5000 # Replace with the port your Tetris game listens on
